apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-deployment
  namespace: fitness-app
  labels:
    app: fitness-tracker
    version: v1
spec:
  replicas: 1              # 1 replica for free tier t2.micro (1GB RAM)
  selector:
    matchLabels:
      app: fitness-tracker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fitness-tracker
        version: v1
    spec:
      containers:
        - name: fitness-app
          image: mohitdocker241/fitness:v1
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: fitness-app-config
            - secretRef:
                name: fitness-app-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3
