apiVersion: v1
kind: Service
metadata:
  name: fitness-app-service
  namespace: fitness-app
  labels:
    app: fitness-tracker
spec:
  selector:
    app: fitness-tracker
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30500      # Access app at EC2_PUBLIC_IP:30500
  type: NodePort           # Works on free tier (no LoadBalancer needed)
