apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitness-tracker-staging
  namespace: argocd
  labels:
    app: fitness-tracker
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Mohitind241/Fitness_Tracker.git
    targetRevision: develop
    path: helm/fitness-app-chart
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fitness-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
