apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-app-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fitness-app-chart.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.PORT | quote }}
  HOST: {{ .Values.config.HOST | quote }}
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  MONGODB_URI: {{ .Values.config.MONGODB_URI | quote }}
  DD_SERVICE: {{ .Values.config.DD_SERVICE | quote }}
  DD_ENV: {{ .Values.config.DD_ENV | quote }}
  DD_VERSION: {{ .Values.config.DD_VERSION | quote }}
