apiVersion: v1
kind: Secret
metadata:
  name: fitness-app-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fitness-app-chart.labels" . | nindent 4 }}
type: Opaque
data:
  DB_User: {{ .Values.secrets.DB_User }}
  DB_Password: {{ .Values.secrets.DB_Password }}
  DD_API_KEY: {{ .Values.secrets.DD_API_KEY }}
